version: '3.7'

services:
  backend:
    container_name: backend
    tty: true
    stdin_open: true
    restart: always
    build:
      context: backend
      dockerfile: 'Dockerfile'
    volumes:
      - './backend:/app'
    ports:
      - 5000:5000
  frontend:
    container_name: frontend
    tty: true
    stdin_open: true
    build:
      context: frontend
      dockerfile: 'Dockerfile'
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - ALGOLIA_APP_ID=${ALGOLIA_APP_ID}
      - ALGOLIA_SEARCH_API_KEY=${ALGOLIA_SEARCH_API_KEY}